/-
GENERATED by scripts/gen_lean_catalogue.py — do not edit by hand.
tests/test_formal_lean_sync.py fails CI when this file drifts from the code.
-/

import SafeTre.Types

namespace SafeTre

/-- The datasets of safetre/query.py::CATALOGUE. -/
def datasets : List String := ["donor_spend", "spend", "wellbeing"]

/-- Public dimensions and their kinds, per dataset. -/
def dimsOf : String → List (String × Kind)
  | "donor_spend" => [("age_band", .cat), ("device_os", .cat), ("income_band", .cat), ("region", .cat), ("sex", .cat)]
  | "spend" => [("age_band", .cat), ("age_rating", .int), ("contains_lootboxes", .bool), ("device_os", .cat), ("event_type", .cat), ("genre", .cat), ("income_band", .cat), ("price_tier", .cat), ("region", .cat), ("sex", .cat)]
  | "wellbeing" => [("age_band", .cat), ("device_os", .cat), ("income_band", .cat), ("region", .cat), ("sex", .cat), ("wave", .int)]
  | _ => []

/-- Public measures, per dataset. -/
def measuresOf : String → List String
  | "donor_spend" => ["lootbox_events", "purchase_events", "total_spend_gbp"]
  | "spend" => ["amount_gbp", "ingame_currency"]
  | "wellbeing" => ["igds_score", "monthly_spend_selfreport", "pgsi_score", "wemwbs_score"]
  | _ => []

/-- Internal-only filter columns (filterable, never grouped or returned). -/
def internalFiltersOf : String → List (String × Kind)
  | "donor_spend" => [("age_years", .int)]
  | "spend" => [("age_years", .int)]
  | "wellbeing" => [("age_years", .int)]
  | _ => []

/-- Internal-only analysis measures for fixed tools (corr). -/
def internalMeasuresOf : String → List String
  | "donor_spend" => ["age_years"]
  | "spend" => []
  | "wellbeing" => []
  | _ => []

/-- Disclosure-role labels (schema.role_of) for every catalogue column
and every forbidden column. Unknown columns get `none` (fail closed). -/
def roleOf? : String → Option Role
  | "age_band" => some .qi
  | "age_rating" => some .r
  | "age_years" => some .qi
  | "amount_gbp" => some .s
  | "contains_lootboxes" => some .r
  | "device_os" => some .qi
  | "donor_id" => some .di
  | "event_type" => some .r
  | "free_text" => some .s
  | "genre" => some .r
  | "igds_score" => some .s
  | "income_band" => some .qi
  | "ingame_currency" => some .s
  | "lootbox_events" => some .s
  | "monthly_spend_selfreport" => some .s
  | "pgsi_score" => some .s
  | "price_tier" => some .r
  | "purchase_events" => some .s
  | "region" => some .qi
  | "sex" => some .qi
  | "total_spend_gbp" => some .s
  | "ts" => some .qi
  | "wave" => some .structural
  | "wemwbs_score" => some .s
  | _ => none

/-- Never-referencable columns: direct identifiers (role DI), free
text, and raw timestamps — absent from every allowlist by construction. -/
def forbiddenColumns : List String := ["donor_id", "free_text", "ts"]

/-- Columns carrying an internal band-aligned range rule
(query.py::INTERNAL_RANGE_RULES; hardening #39). -/
def rangeRuledColumns : List String := ["age_years"]

/-- The operators offered on such a column: band-aligned ranges only.
Equality and membership on the raw value are not expressible. -/
def internalRangeOps : String → List Op
  | "age_years" => [.ge, .le]
  | _ => []

/-- The permitted edge values, per operator. -/
def internalRangeEdges : String → List (Op × List Int)
  | "age_years" => [(.ge, [13, 16, 18, 25, 35, 50]), (.le, [15, 17, 24, 34, 49, 69])]
  | _ => []

/-- The public bands the rule is aligned to, as closed intervals:
the `>=` edges are their lower bounds, the `<=` edges their upper
bounds. Proofs.lean checks that pairing really does partition. -/
def internalBands : String → List (Int × Int)
  | "age_years" => [(13, 15), (16, 17), (18, 24), (25, 34), (35, 49), (50, 69)]
  | _ => []

/-- The engine's PUBLIC view columns (DuckDB `DESCRIBE`, live views). -/
def publicViewColumns : String → List String
  | "donor_spend" => ["age_band", "sex", "region", "income_band", "device_os", "total_spend_gbp", "purchase_events", "lootbox_events"]
  | "spend" => ["age_band", "sex", "region", "income_band", "device_os", "genre", "contains_lootboxes", "price_tier", "age_rating", "event_type", "amount_gbp", "ingame_currency"]
  | "wellbeing" => ["age_band", "sex", "region", "income_band", "device_os", "wave", "pgsi_score", "igds_score", "wemwbs_score", "monthly_spend_selfreport"]
  | _ => []

/-- The engine's INTERNAL unit-view columns (donor_id, age_years present:
these views exist for fixed tools and disclosure machinery only). -/
def unitViewColumns : String → List String
  | "donor_spend" => ["donor_id", "age_years", "age_band", "sex", "region", "income_band", "device_os", "total_spend_gbp", "purchase_events", "lootbox_events"]
  | "spend" => ["donor_id", "age_years", "age_band", "sex", "region", "income_band", "device_os", "genre", "contains_lootboxes", "price_tier", "age_rating", "event_type", "amount_gbp", "ingame_currency"]
  | "wellbeing" => ["donor_id", "age_years", "age_band", "sex", "region", "income_band", "device_os", "wave", "pgsi_score", "igds_score", "wemwbs_score", "monthly_spend_selfreport"]
  | _ => []

end SafeTre
