"""Regenerate the Lean formal artifacts from the live code (R16).

Two outputs, both committed:
- formal/lean/SafeTre/Catalogue.lean — the catalogue, its disclosure-role
  labels (schema.role_of), and the engine's actual view columns, as Lean
  definitions;
- formal/lean/SafeTre/Cases.lean — a covering enumeration of QuerySpecs
  paired with the engine's compiled SQL text and bound-parameter count.
  SafeTre/Proofs.lean recompiles every case inside Lean (render ∘ compile)
  and proves exact string equality, pinning the abstract compiler to
  engine.compile_query.

tests/test_formal_lean_sync.py regenerates both in-memory and fails CI on
drift, so the Lean proofs always speak about the code as it is.

Usage:
    uv run python scripts/gen_lean_catalogue.py           # check (exit 1 on drift)
    uv run python scripts/gen_lean_catalogue.py --write   # rewrite the artifacts
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd                                            # noqa: E402

from safetre import dataset as _dataset                        # noqa: E402
from safetre.engine import QueryEngine, compile_query         # noqa: E402
from safetre.procedures import REGISTRY                       # noqa: E402
from safetre.query import (                                       # noqa: E402
    CATALOGUE, INTERNAL_RANGE_RULES, Filter, Measure, QuerySpec,
)
from safetre.schema import declared_domain, identifier_columns, role_of  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGUE_LEAN = os.path.join(ROOT, "formal", "lean", "SafeTre", "Catalogue.lean")
CASES_LEAN = os.path.join(ROOT, "formal", "lean", "SafeTre", "Cases.lean")

HEADER = """/-
GENERATED by scripts/gen_lean_catalogue.py — do not edit by hand.
tests/test_formal_lean_sync.py fails CI when this file drifts from the code.
-/
"""

_KIND = {"cat": ".cat", "bool": ".bool", "int": ".int"}
_ROLE = {"DI": ".di", "QI": ".qi", "S": ".s", "R": ".r", "meta": ".structural"}
_OP = {"==": ".eq", "!=": ".ne", "<": ".lt", "<=": ".le",
       ">": ".gt", ">=": ".ge", "in": ".isIn"}


def forbidden_columns() -> list[str]:
    """Never-referencable columns: direct identifiers plus free text and raw
    timestamps (the explicit by-construction exclusions of query.py)."""
    return sorted(identifier_columns() | {"free_text", "ts"})


def _empty_base_tables() -> dict[str, "pd.DataFrame"]:
    """One empty, correctly-typed frame per base table of the ACTIVE dataset.

    This used to be `synth.generate()`, which knows only the packaged demo's
    tables — so on any operator dataset the generator died with
    `KeyError: 'events'` and the Lean proofs could not be regenerated for the
    catalogue they were supposed to be about. The committed theorems then
    described the demo's columns rather than the study's, which is the one
    thing a proof must not do quietly.

    Only column NAMES are wanted here (`DESCRIBE` on the created views), so no
    data are needed and none are invented: empty frames with the right dtypes
    let DuckDB create every view — including the derived `SUM(CASE ...)`
    columns, which need their operand to be numeric — and describe it. It is
    also the stricter choice, because a readback that cannot see any values
    cannot accidentally depend on one.
    """
    definition = _dataset.active()
    # output column name -> declared kind, gathered from every view
    kinds: dict[str, str] = {}
    for view in definition.datasets.values():
        kinds.update(view.dims)
        kinds.update(view.internal_filters)
        for measure in list(view.measures) + list(view.internal_measures):
            kinds[measure] = "num"

    dtypes = {"cat": "object", "bool": "bool", "int": "int64", "num": "float64"}
    tables: dict[str, pd.DataFrame] = {}
    for name, columns in definition.tables.items():
        tables[name] = pd.DataFrame({
            column: pd.Series([], dtype=dtypes.get(kinds.get(column, "cat"), "object"))
            for column in columns
        })
    return tables


def _view_columns() -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """The engine's real view columns, read back from DuckDB itself."""
    engine = QueryEngine(_empty_base_tables())
    public, unit = {}, {}
    for ds in sorted(CATALOGUE):
        public[ds] = [r[0] for r in engine.con.execute(f'DESCRIBE "{ds}"').fetchall()]
        unit[ds] = [r[0] for r in engine.con.execute(f'DESCRIBE "_{ds}_u"').fetchall()]
    return public, unit


def _str_list(items) -> str:
    return "[" + ", ".join(json.dumps(i) for i in items) + "]"


def _kinded_list(mapping: dict[str, str]) -> str:
    return "[" + ", ".join(f"({json.dumps(c)}, {_KIND[k]})"
                           for c, k in sorted(mapping.items())) + "]"


def _match_fn(name: str, result_type: str, arms: dict[str, str],
              default: str) -> list[str]:
    lines = [f"def {name} : String → {result_type}"]
    for key in sorted(arms):
        lines.append(f"  | {json.dumps(key)} => {arms[key]}")
    lines.append(f"  | _ => {default}")
    return lines


def _bands(rule: dict) -> list[tuple[int, int]]:
    """The declared bands, as (lower, upper) pairs.

    Derived by pairing the `>=` edges with the `<=` edges in order — the
    pairing IS the claim that the rule is band-aligned, and Lean checks it
    (`bands_are_a_partition`, `edges_are_the_band_boundaries`). A rule whose
    edge lists disagree in length is refused here rather than emitted as a
    band structure the proofs would then have to accommodate.
    """
    ge, le = rule["edges"][">="], rule["edges"]["<="]
    if len(ge) != len(le):
        raise SystemExit(
            f"internal range rule has {len(ge)} '>=' edges and {len(le)} '<=' "
            "edges: they cannot describe the same bands")
    return list(zip(ge, le, strict=True))


def catalogue_lean() -> str:
    public, unit = _view_columns()
    columns: set[str] = set()
    for info in CATALOGUE.values():
        columns |= set(info["dims"]) | set(info["measures"])
        columns |= set(info["internal_filters"]) | set(info["internal_measures"])

    lines: list[str] = [HEADER, "import SafeTre.Types", "", "namespace SafeTre", ""]
    lines.append("/-- The datasets of safetre/query.py::CATALOGUE. -/")
    lines.append(f"def datasets : List String := {_str_list(sorted(CATALOGUE))}")
    lines.append("")
    lines.append("/-- Public dimensions and their kinds, per dataset. -/")
    lines += _match_fn("dimsOf", "List (String × Kind)",
                       {ds: _kinded_list(CATALOGUE[ds]["dims"]) for ds in CATALOGUE},
                       "[]")
    lines.append("")
    lines.append("/-- Public measures, per dataset. -/")
    lines += _match_fn("measuresOf", "List String",
                       {ds: _str_list(sorted(CATALOGUE[ds]["measures"]))
                        for ds in CATALOGUE}, "[]")
    lines.append("")
    lines.append("/-- Internal-only filter columns (filterable, never grouped or returned). -/")
    lines += _match_fn("internalFiltersOf", "List (String × Kind)",
                       {ds: _kinded_list(CATALOGUE[ds]["internal_filters"])
                        for ds in CATALOGUE}, "[]")
    lines.append("")
    lines.append("/-- Internal-only analysis measures for fixed tools (corr). -/")
    lines += _match_fn("internalMeasuresOf", "List String",
                       {ds: _str_list(sorted(CATALOGUE[ds]["internal_measures"]))
                        for ds in CATALOGUE}, "[]")
    lines.append("")
    lines.append("/-- Disclosure-role labels (schema.role_of) for every catalogue column")
    lines.append("and every forbidden column. Unknown columns get `none` (fail closed). -/")
    role_arms = {c: f"some {_ROLE[role_of(c)]}"
                 for c in sorted(columns | set(forbidden_columns()))}
    lines += _match_fn("roleOf?", "Option Role", role_arms, "none")
    lines.append("")
    lines.append("/-- Never-referencable columns: direct identifiers (role DI), free")
    lines.append("text, and raw timestamps — absent from every allowlist by construction. -/")
    lines.append(f"def forbiddenColumns : List String := {_str_list(forbidden_columns())}")
    lines.append("")
    lines.append("/-- Columns carrying an internal band-aligned range rule")
    lines.append("(query.py::INTERNAL_RANGE_RULES; hardening #39). -/")
    lines.append("def rangeRuledColumns : List String := "
                 + _str_list(sorted(INTERNAL_RANGE_RULES)))
    lines.append("")
    lines.append("/-- The operators offered on such a column: band-aligned ranges only.")
    lines.append("Equality and membership on the raw value are not expressible. -/")
    lines += _match_fn(
        "internalRangeOps", "List Op",
        {c: "[" + ", ".join(_OP[o] for o in rule["ops"]) + "]"
         for c, rule in INTERNAL_RANGE_RULES.items()}, "[]")
    lines.append("")
    lines.append("/-- The permitted edge values, per operator. -/")
    lines += _match_fn(
        "internalRangeEdges", "List (Op × List Int)",
        {c: "[" + ", ".join(
            f"({_OP[o]}, [" + ", ".join(str(v) for v in vs) + "])"
            for o, vs in rule["edges"].items()) + "]"
         for c, rule in INTERNAL_RANGE_RULES.items()}, "[]")
    lines.append("")
    lines.append("/-- The public bands the rule is aligned to, as closed intervals:")
    lines.append("the `>=` edges are their lower bounds, the `<=` edges their upper")
    lines.append("bounds. Proofs.lean checks that pairing really does partition. -/")
    lines += _match_fn(
        "internalBands", "List (Int × Int)",
        {c: "[" + ", ".join(f"({lo}, {hi})" for lo, hi in _bands(rule)) + "]"
         for c, rule in INTERNAL_RANGE_RULES.items()}, "[]")
    lines.append("")
    lines.append("/-- The engine's PUBLIC view columns (DuckDB `DESCRIBE`, live views). -/")
    lines += _match_fn("publicViewColumns", "List String",
                       {ds: _str_list(public[ds]) for ds in public}, "[]")
    lines.append("")
    lines.append("/-- The engine's INTERNAL unit-view columns (donor_id, age_years present:")
    lines.append("these views exist for fixed tools and disclosure machinery only). -/")
    lines += _match_fn("unitViewColumns", "List String",
                       {ds: _str_list(unit[ds]) for ds in unit}, "[]")
    lines.append("")
    lines.append("end SafeTre")
    return "\n".join(lines) + "\n"


# --- covering case enumeration -------------------------------------------------

def _example_value(kind: str, column: str):
    domain = declared_domain(column)
    if kind == "bool":
        return True
    if kind == "int":
        return int(domain[0]) if domain else 18
    return str(domain[0]) if domain else "x"


def _filter_variants(ds: str) -> list[list[dict]]:
    """Filter-shape variants covering every operator arm of the renderer:
    none, scalar cat, scalar int, a 2-value in-list, an internal-column
    filter (routes to the unit view), and a MAX_FILTERS-sized mix."""
    cat = CATALOGUE[ds]
    dims = cat["dims"]
    cat_dims = sorted(c for c, k in dims.items() if k == "cat")
    int_dims = sorted(c for c, k in dims.items() if k == "int")
    internal = sorted(cat["internal_filters"])

    def f(column, op, kind):
        if op == "in":
            domain = declared_domain(column)
            values = ([str(v) for v in domain[:2]] if kind == "cat" and domain
                      else [_example_value(kind, column)] * 2)
            return {"column": column, "op": "in", "value": values}
        return {"column": column, "op": op, "value": _example_value(kind, column)}

    variants: list[list[dict]] = [[]]
    if cat_dims:
        variants.append([f(cat_dims[0], "==", "cat")])
        variants.append([f(cat_dims[0], "in", "cat")])
    if int_dims:
        variants.append([f(int_dims[0], "<=", "int")])
    if internal:
        variants.append([f(internal[0], ">=", "int")])
    mix = (([f(c, "==", "cat") for c in cat_dims[:3]]
            + [f(c, ">", "int") for c in int_dims[:1]]
            + [f(c, "!=", "cat") for c in cat_dims[3:4]])[:5])
    if len(mix) >= 2:
        variants.append(mix)
    return variants


def case_specs() -> list[QuerySpec]:
    """The covering enumeration: every registered measure configuration of
    every dataset, crossed once with the group-by depths (0–3) and once with
    the filter variants. The renderer is compositional, so covering each axis
    against a fixed other axis pins every fragment the engine can emit."""
    specs: list[QuerySpec] = []
    for ds in sorted(CATALOGUE):
        cat = CATALOGUE[ds]
        dims = sorted(cat["dims"])
        groupings = [[], dims[:1], dims[:2], dims[:3]]
        for _, proc in sorted(REGISTRY.items()):
            for config in proc.measure_configs(cat):
                measure = Measure(**config)
                for grouping in groupings:
                    specs.append(QuerySpec(dataset=ds, measure=measure,
                                           group_by=grouping, filters=[]))
                for filters in _filter_variants(ds):
                    specs.append(QuerySpec(
                        dataset=ds, measure=measure, group_by=dims[:1],
                        filters=[Filter(**fd) for fd in filters]))
    return specs


def _lean_opt(value: str | None) -> str:
    return f"some {json.dumps(value)}" if value is not None else "none"


def _lean_filter(f: Filter) -> str:
    nvals = len(f.value) if f.op == "in" else 1
    # The model carries an integer filter value ONLY so the band-alignment rule
    # (#39) is statable; `Proofs.compile_ignores_filter_values` proves nothing
    # downstream can read it, which is what keeps "values never reach SQL" true.
    scalar_int = (f.op != "in" and isinstance(f.value, int)
                  and not isinstance(f.value, bool))
    value = f"some {f.value}" if scalar_int else "none"
    return f"⟨{json.dumps(f.column)}, {_OP[f.op]}, {nvals}, {value}⟩"


def _lean_spec(s: QuerySpec) -> str:
    m = (f"⟨.{ {'sum_sq': 'sumSq'}.get(s.measure.fn, s.measure.fn) }, "
         f"{_lean_opt(s.measure.column)}, {_lean_opt(s.measure.x)}, "
         f"{_lean_opt(s.measure.y)}⟩")
    fs = "[" + ", ".join(_lean_filter(f) for f in s.filters) + "]"
    return f"⟨{json.dumps(s.dataset)}, {m}, {_str_list(s.group_by)}, {fs}⟩"


def cases_lean() -> str:
    lines = [HEADER, "import SafeTre.Types", "", "namespace SafeTre", ""]
    lines.append("/-- The covering enumeration: (spec, engine SQL, bound-parameter count).")
    lines.append("The SQL strings are engine.compile_query's actual output; Proofs.lean")
    lines.append("proves `render (compile spec)` reproduces every one exactly. -/")
    lines.append("def cases : List (Spec × String × Nat) := [")
    entries = []
    for spec in case_specs():
        plan = compile_query(spec)
        entries.append(f"  ({_lean_spec(spec)},\n"
                       f"   {json.dumps(plan.sql)}, {len(plan.params)})")
    lines.append(",\n".join(entries))
    lines.append("]")
    lines.append("")
    lines.append("end SafeTre")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="rewrite the artifacts")
    args = ap.parse_args()

    fresh = {CATALOGUE_LEAN: catalogue_lean(), CASES_LEAN: cases_lean()}
    drift = False
    for path, text in fresh.items():
        if not os.path.exists(path) or open(path).read() != text:
            drift = True
            print(f"{os.path.relpath(path, ROOT)} is stale")

    if args.write:
        for path, text in fresh.items():
            with open(path, "w") as fh:
                fh.write(text)
        print("lean formal artifacts rewritten")
        return 0
    if drift:
        print("run: uv run python scripts/gen_lean_catalogue.py --write")
        return 1
    print("lean formal artifacts in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
